### PR TITLE
Profile V1.0

### PR DESCRIPTION
**Pull request by Raushawn**

### CODE REVIEW

**Comment by A-Hazzard** [comment]
Review Facebook on mobile


This is how it looks on my device


Also one of the reasons for this because i uploaded a landscape photo. Tell cursor to only let the user upload images for the  banner that has a landscape orientation. And try for the avatar(profile picture) to hover over the banner on the left like Facebook.

**Review by uptech2021 — CHANGES_REQUESTED** [review]
image
Hey, thanks for the update. On the profile page I'm not seeing my profile picture

image

You also need to look into the design of the post form, on the left has a bright white space on pc

**Review by uptech2021 — CHANGES_REQUESTED** [review]
# Banner Upload and Image Cropper Issues

### Banner Upload

- **Orientation Restriction:** Currently, the platform allows portrait images to be uploaded as banners, as shown in this screenshot: [Screenshot_20241021_105827_Edge](https://github.com/user-attachments/assets/016bf40b-5958-47f4-bffc-d710fd7572b1). 
Please restrict banner uploads to landscape orientations only. When an invalid orientation is detected, display an error message that explicitly states "Only landscape images are allowed" and provides examples of acceptable image dimensions (e.g., 1920 x 1080, 1600 x 600, 1280 x 720, 2560 x 1440 etc you can get some appropriate ones from cursor for our usecase). This will help users understand the requirement and choose the correct files.
- **Preview Size:** The banner preview in the upload modal is too large. Please implement a fixed width and height for all preview images and use object-fit to ensure they are displayed correctly. This will maintain a consistent look and improve the user experience. The image previews on the jobs and market pages are good examples of the desired behavior.

## Image Cropper:

- **Preview Bug:** There is a bug where the first uploaded image does not preview. I have sent you a video demonstration on WhatsApp.
- **Cropper Accessibility:** Sometimes the cropper for the profile picture does not appear on the first attempt. To improve this, the cropper should be displayed as a pop-up modal over the "Edit Profile" modal. This would make it more prominent and user-friendly.

## Scrolling Issue:

- After cropping and uploading a banner image, I am unable to scroll down the page. This issue is also demonstrated in the WhatsApp video.

### Suggested Logic for Orientation Check:

```bash
If image orientation === portrait THEN
    Display error message: "Only landscape images are allowed (e.g., 1920 x 1080)." `

**Review by A-Hazzard — CHANGES_REQUESTED** [review]
Comments Added On Jira

**Pull request merged**
